tachej:
    path:     /profil/tachej
    defaults: { _controller: "VworkitBundle:Tache:affichetache" }

tache:
    path:     /profil/tache
    defaults: { _controller: "VworkitBundle:Tache:index" }

mestaches:
    path:     /profil/tache/mestaches
    defaults: { _controller: "VworkitBundle:Tache:Mestaches" }

mestachesassocie:
    path:     /profil/tache/mestachesassocie
    defaults: { _controller: "VworkitBundle:Tache:MestachesAssocie" }

tache_show:
    path:     /profil/tache/{id}/show
    defaults: { _controller: "VworkitBundle:Tache:show" }

tache_new:
    path:     /profil/tache/new
    defaults: { _controller: "VworkitBundle:Tache:new" }

tache_create:
    path:     /profil/tache/create
    defaults: { _controller: "VworkitBundle:Tache:create" }
    requirements: { _method: post }

tache_edit:
    path:     /profil/tache/{id}/edit
    defaults: { _controller: "VworkitBundle:Tache:edit" }

tache_update:
    path:     /profil/tache/{id}/update
    defaults: { _controller: "VworkitBundle:Tache:update" }
    requirements: { _method: post|put }

tache_delete:
    path:     /profil/tache/{id}/delete
    defaults: { _controller: "VworkitBundle:Tache:delete" }
    #requirements: { _method: post|delete }

tachetache_delete:
    path:     /profil/tache/{id}/delete
    defaults: { _controller: "VworkitBundle:Tache:deletetache" }

tacheReunion:
    pattern:  /profil/tache/reunion/{reunion}
    defaults: { _controller: VworkitBundle:Reunion:tacheReunion }

progressionTache:
    pattern:  /profil/tache/progression/{progression}
    defaults: { _controller: VworkitBundle:Progression:progressions }