security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/new, role: ROLE_USER }
        - { path: ^/.*/lister, role: ROLE_USER }
        - { path: ^/.*/deposer, role: ROLE_USER }
        - { path: ^/.*/deposer, role: ROLE_USER }
        - { path: ^/.*/voir, role: ROLE_USER }
        - { path: ^/allfavoris, role: ROLE_USER }
        - { path: ^/user/visite, role: ROLE_USER }
        - { path: ^/favoris/.*, role: ROLE_USER }
        - { path: ^/info, role: ROLE_USER }
        - { path: ^/examen, role: ROLE_USER }
        - { path: ^/invite, role: ROLE_USER }
        - { path: ^/finance, role: ROLE_USER }
        - { path: ^/parametre, role: ROLE_USER }
        - { path: ^/reseau, role: ROLE_USER }
        - { path: ^/notification, role: ROLE_USER }
        - { path: ^/.*/deposer, role: ROLE_USER }
        - { path: ^/message/listeenvoie, role: ROLE_USER }
        - { path: ^/message/listemessage, role: ROLE_USER }
        - { path: ^/message/listearchive, role: ROLE_USER }
        - { path: ^/portfolio/lister, role: ROLE_USER }
        - { path: ^/portfolio/new, role: ROLE_USER }
        - { path: ^/profil, role: ROLE_USER }
        - { path: ^/apropos, role: ROLE_USER }
        - { path: ^/litige, role: ROLE_USER }
        - { path: ^/.*/modifier, role: ROLE_USER }
        - { path: ^/.*/new, role: ROLE_USER }
        - { path: ^/historique, role: ROLE_USER }
        - { path: ^/projet, role: ROLE_USER }
