<?php

namespace Utilisateur\UtilisateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PortfolioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioRepository extends EntityRepository
{
	public function byUser($id_user){
        $req = $this->createQueryBuilder('p')
                    ->select('p')
                    ->where('p.user =:user')
                    ->orderBy('p.id')
                    ->setParameter('user', $id_user);
        return $req->getQuery()->getResult();
    }

    public function ByPortfolio($id_user){
        $req = $this->createQueryBuilder('p')
                    ->select('p')
                    ->where('p.user =:user')
                    ->orderBy('p.id')
                    ->setParameter('user', $id_user);
        return $req->getQuery()->getResult();
    }
}
