<?php

namespace Utilisateur\UtilisateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RecommandationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommandationRepository extends EntityRepository
{
    public function ByRecom($id_user){
        $req = $this->createQueryBuilder('p')
                    ->select('p')
                    ->where('p.to =:user')
                    ->orderBy('p.id')
                    ->setParameter('user', $id_user);
        return $req->getQuery()->getResult();
    }

    
}
