<?php

namespace Utilisateur\UtilisateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseRepository extends EntityRepository
{
    public function findByrep($id){
        $req = $this->createQueryBuilder('p')
                    ->select('p')
                    ->where('p.message =:message')
                    
                    
                    ->setParameter('message', $id);
                    
        return $req->getQuery()->getResult();
    }
}
