<?php

namespace Utilisateur\UtilisateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VisiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteRepository extends EntityRepository
{
	public function findUser($useractuel){
        $req = $this->createQueryBuilder('p')
                    ->select('p')
                    ->where('p.to =:user')
                    
                    ->groupBy('p.datevisite')
                    ->setParameter('user', $useractuel);
        return $req->getQuery()->getResult();
    }
}
