<?php

namespace Vworkit\VworkitBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends EntityRepository
{
	public function byCategorieindex(){
        $req = $this->createQueryBuilder('p')
                    ->select('p');
                    
                    $req->setMaxResults(12);
        return $req->getQuery()->getResult();
    }
    
    public function findAll1(){
        
        $req = $this->createQueryBuilder('p')
                    ->select('p')
                    ->groupBy('p.id');
        return $req->getQuery()->getResult();
    }

    
}
