<?php

namespace Vworkit\VworkitBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DureeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DureeRepository extends EntityRepository
{
}
