<?php

namespace Vworkit\VworkitBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends EntityRepository
{
    public function findByUser($id){
        $req = $this->createQueryBuilder('p')
                    
                    ->join('p.projet','f')->select('f')
                    ->where('f.user =:id')
                    ->select('p')
                    
                    ->setParameter('id', $id);
        return $req->getQuery()->getResult();
    }
    
    
    
    public function getNb($id_user) {
 
        return $this->createQueryBuilder('p')
                        ->join('p.projet','f')->select('f')
                        ->where('f.user =:id')
                        ->select('COUNT(p)')
                        
                        ->setParameter('id', $id_user)
                        ->getQuery()
 
                        ->getSingleScalarResult();
 
    }
    
    public function byProjet($id){
        $req = $this->createQueryBuilder('p')
                    ->select('p')
                    ->where('p.projet =:id')
                    ->orderBy('p.id')
                    ->setParameter('id', $id);
        return $req->getQuery()->getResult();
    }
    
    public function byUser($id_user){
        $req = $this->createQueryBuilder('p')
                    ->select('p')
                    ->where('p.user =:user')
                    
                    ->orderBy('p.id')
                    ->setParameter('user', $id_user);
        return $req->getQuery()->getResult();
    }
    
}
