<?php

namespace Vworkit\VworkitBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheRepository extends EntityRepository
{
    public function byProgression($progression,$user){
        $req = $this->createQueryBuilder('p')
                    ->join('p.reunion','f')->select('f')
                    ->where('f.prestataire =:id')
                    ->AndWhere('p.progression =:progression')
                    ->select('p')
                    ->orderBy('p.id')
                    ->setParameter('progression', $progression)
                    ->setParameter('id', $user);
        return $req->getQuery()->getResult();
    }
    
    public function RechercheByReunion($reunion){
        $req = $this->createQueryBuilder('p')
                    ->select('p')
                    ->where('p.reunion =:id')
                    ->orderBy('p.id')
                    ->setParameter('id', $reunion);
        return $req->getQuery()->getResult();
    }
    
    public function RechercheByUser($id){
        $req = $this->createQueryBuilder('p')
                    
                    ->join('p.reunion','f')->select('f')
                    ->where('f.porteur =:id')
                    ->orWhere('f.prestataire =:id')
                    ->select('p')
                    
                    ->setParameter('id', $id);
        return $req->getQuery()->getResult();
    }
    
    public function RechercheByMine($id){
        $req = $this->createQueryBuilder('p')
                    
                    ->join('p.reunion','f')->select('f')
                    ->where('f.prestataire =:id')
                    
                    ->select('p')
                    
                    ->setParameter('id', $id);
        return $req->getQuery()->getResult();
    }
    
    public function RechercheByAssocie($id){
        $req = $this->createQueryBuilder('p')
                    
                    ->join('p.reunion','f')->select('f')
                    ->where('f.porteur =:id')
                    
                    ->select('p')
                    
                    ->setParameter('id', $id);
        return $req->getQuery()->getResult();
    }
    
}
